### ISSUE TITLE
Separate Tag Aliases from Config File

### ISSUE THREAD

**Issue by tecknojock** [xiagu/jekyll-rp-logs#53]
Enable us to edit aliases and implications outside the config file so that changes dont require relaunching jekyll.

**Comment by irisfofs** [comment]
This would also be a big help for #28 (and eventually #54) which also adds more bloat to config files.

I'm not sure how easy it would be to rebuild the entire site when a change is detected in one of these files (or hook into the change detection to begin with). 

It's fairly low priority for me though, since it involves some complicated mucking about with Jekyll internals (probably, at least).
